// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAufNZKzNv2cDjz_ABN99JgE9iYMMYcK3c',
    appId: '1:324639366248:web:269ed3961e7d4c3b6cafdd',
    messagingSenderId: '324639366248',
    projectId: 'kiinteistoapp',
    authDomain: 'kiinteistoapp.firebaseapp.com',
    databaseURL: 'https://kiinteistoapp-default-rtdb.firebaseio.com',
    storageBucket: 'kiinteistoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGLalJnmxP9aNXIIoAXg-udpI8zDD1iwg',
    appId: '1:324639366248:android:4a4f51718622f4236cafdd',
    messagingSenderId: '324639366248',
    projectId: 'kiinteistoapp',
    databaseURL: 'https://kiinteistoapp-default-rtdb.firebaseio.com',
    storageBucket: 'kiinteistoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxHiuH5D4FeSEQOHRiZMapcSNIB6QBLY',
    appId: '1:324639366248:ios:52fb367f0a24bd0f6cafdd',
    messagingSenderId: '324639366248',
    projectId: 'kiinteistoapp',
    databaseURL: 'https://kiinteistoapp-default-rtdb.firebaseio.com',
    storageBucket: 'kiinteistoapp.appspot.com',
    iosClientId: '324639366248-8laqd6mcgl44iqg2jff7obm4ts68mreb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterKiinteistohuolto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMxHiuH5D4FeSEQOHRiZMapcSNIB6QBLY',
    appId: '1:324639366248:ios:52fb367f0a24bd0f6cafdd',
    messagingSenderId: '324639366248',
    projectId: 'kiinteistoapp',
    databaseURL: 'https://kiinteistoapp-default-rtdb.firebaseio.com',
    storageBucket: 'kiinteistoapp.appspot.com',
    iosClientId: '324639366248-8laqd6mcgl44iqg2jff7obm4ts68mreb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterKiinteistohuolto',
  );
}
